---
title: "Welcome to Leo Kepeng Li"
description: |
  Welcome to my new blog. We hope you enjoy 
  reading what we have to say!
author:
  - name: Kepeng Li
    affiliation: My Sweet Home
date: 08-19-2024
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

This page is designed for teaching and self-learning purpose. I plan to include contents ranging from R entry-level basics to logistic regression and interaction plotting using `ggplot2`. 

Once again, this page may contain some information that I developed to suit my personal use or based on my past user experiences. It is not necessarily about which code or which package is more recommended over other alternative options. Everyone would build their own "package library" as a result of individual habit, so I personally believe that there is no best solution to one particular coding system. It truly depends on your preferences and needs. If you would like to discuss some specific issues on one or several R topics, please leave a comment below or contact via my personal email and channel: <mrmsstyle101@gmail.com> and <https://kepengli.netlify.app>. 

## 1. R basics

### Introduction of R and RStudio

R is a powerful, open-source, free software for statistical analysis and graphics. It is 'a collaborative project with many contributors' and having numerous Packages utilized for different purposes. One can download the official R software via its website: <https://www.r-project.org>. 

To better use and manage projects in R, I use RStudio as my main development environment tool. As the user interface of RStudio is much flexible and user-friendly, especially to new users, I would recommend people learn R language using RStudio from the beginning as this will largely improve output efficiency and help one quickly get used to the programming language environment. The official website of RStudio and download link can be found here: <https://posit.co/downloads>.